mybatis:
  check-config-location: true
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.example.dynamicschedule.bean
server:
  port: 8888
spring:
  datasource:
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 50
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    password: root
    poolPreparedStatements: false
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: root
    validationQuery: SELECT 1 FROM DUAL
